# Generated by Django 4.2.5 on 2023-10-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='titel',
            new_name='title',
        ),
    ]
