# Generated by Django 4.2.5 on 2023-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
