# Generated by Django 4.2.5 on 2023-10-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_contact_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
